import json
import google.generativeai as genai
from fastapi import HTTPException, status
from ..core.config import settings

class AIDetectorService:
    def __init__(self):
        if settings.GEMINI_API_KEY:
            genai.configure(api_key=settings.GEMINI_API_KEY)
            try:
                self.model = genai.GenerativeModel('gemini-2.5-flash')
            except Exception:
                # Fallback as requested by user
                self.model = genai.GenerativeModel('gemini-2.5-pro')
        else:
            self.model = None

    async def detect_ai_generated(self, resume_text: str) -> dict:
        if not self.model:
            raise HTTPException(
                status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
                detail="Gemini API key is not configured."
            )

        prompt = f"""
        Analyze the following resume text and determine the probability that it was generated by an AI (like ChatGPT or Gemini).
        
        Return the result STRICTLY as a JSON object with the following structure:
        {{
            "ai_generated_probability": number (0-100),
            "confidence_level": "Low" | "Medium" | "High",
            "reasoning": "A brief explanation of why you gave this score"
        }}

        Resume Text:
        {resume_text}
        """

        try:
            response = self.model.generate_content(
                prompt,
                generation_config=genai.types.GenerationConfig(
                    response_mime_type="application/json",
                ),
            )
            
            # Safely parse JSON response
            try:
                result = json.loads(response.text)
                return result
            except json.JSONDecodeError:
                # Fallback in case the model returns something slightly off
                print(f"Failed to parse JSON response: {response.text}")
                raise ValueError("AI model returned an invalid response format.")

        except Exception as e:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=f"Gemini API Error: {str(e)}"
            )

ai_detector_service = AIDetectorService()
